export default {
  lang: 'Afrikaans',
  failed: 'Aksie het misluk',
  success: 'Aksie was suksesvol',
  RPCCheck: 'Alle stelsels is aanlyn',
  RPCCheck_fail: "Dit blyk dat ons RPC tans nie gesinkroniseer is nie, saldo 's kan verkeerd wees en TX's sal nie werk nie.Funksionaliteit sal so gou moontlik herstel word.",
  // Routes
  routes: {
    config: 'Opset',
    settings: 'Instellings',
    send: 'Stuur',
    txs: 'Transaksies',
    receive: 'Ontvang',
    home: 'Huis',
    supcurr: 'Ondersteunde geldeenhede',
    suplang: 'Ondersteunde tale',
    keystore: 'Generate Keystore',
    supnet: 'Supported Networks',
  },
  lending_dapp: {
    accept: 'Accept',
    decline: 'Decline',
    beta: 'Mobile Beta',
    myContracts: 'My Contracts',
    toRemove: "If you'd like to remove a contract, simply press on the contract.",
    type: 'Type',
    available: 'Available',
    noContractsOrLoading: 'No Contracts found OR Data is Loading...',
    welcome: 'Welcome to the Ether-1 Lending Dapp',
    desc: `The Ether-1 node staking dashboard provides ETHO stake holders and node
    operators a chance to come together and profit from an Ether-1 node,
    providing a valuable service to the Ether-1 & ethoFS networks, all while
    remaining completely decentralized in nature.`,
    desc_expanded: `Our staking is unique because it doesn’t increase ETHO inflation and it
    not only locks up coins, it also provides more fully operational
    Ether-1/ethoFS nodes to make our community data swarm even greater.`,
    termsHeading: 'Terms of Agreement',
    term1: `Borrower and Lender both agree they understand and consent to the
    terms and conditions below upon entering their private keys on
    this website.`,
    term2: `After claiming an available staking contract, Borrower has 50,000
    blocks to setup an active and paying Ether-1 node using Lender's
    smart contract stake. Failure to do so gives Lender the option to
    collect Borrower's origination fee.`,
    term3: `When Borrower's Ether-1 node produces its first reward payment
    within 50,000 blocks, contract status is changed from inactive to
    active. The contract status is changed back to inactive if the
    Borrower's node loses its paying status for a single payment
    period. Lender has the option to reset/remove an inactive contract
    between 50,000 and 199,999 blocks and collect Borrower’s
    origination fee.`,
    term4: `Lender can reset/remove an active contract after 200,000 blocks
    with the origination fee returned to the Borrower. Borrower can
    abandon an active contract after 200,000 blocks with the
    origination fee returned to the Borrower.`,
    term5: `If Borrower abandons an active contract within the first 200,000
    blocks, security deposit is forfeited to the Lender.`,
    term6: `Lender can cancel an active contract only after 200,000 blocks,
    with 95% of the origination fee returned to the Borrower.`,
    notes: 'NOTES',
    note1: `Lender has the option to stipulate additional Terms and Conditions
    within each staking contract. By claiming the staking contract,
    Borrower agrees to Lender's additional Term and Conditions.`,
    note2: `Lender's additional stipulated Terms and Conditions do not
    supersede Smart Contract rules (1) through (6) listed above.`,
    nodeTypeAndSpilt: 'Select Node Type & Select Lender Split',
    create: 'Create A Lending Contract',
    get: 'Get Contracts',
    select: 'Select Node Type',
    split: 'Select Desired Lender Split %',
    fee: 'Select Desired Origination Fee',
    addTCs: 'Enter Addition Terms & Conditions',
    badNetwork: 'Incorrect Network',
    badDesc: 'Please Connect to the Ether-1 Network, if you wish to access the Staking dApp.',
    success: 'Success!',
    smsg: 'Your Lending Contract has been add to the staking platform.',
    error: 'ERROR',
    emsg1: 'You do NOT have enough balance to deploy this stake. You currently have',
    emsg2: 'ETHO, You need a total of',
    removedmsg: 'Your Lending Contract has been removed from the staking platform.',
  },
  nodes: {
    active: 'Active',
    stats: 'Node Stats',
    rewards: 'Last Reward for',
    owned: 'Owned Node Type',
    balance: 'Collateral Balance',
    status: 'Node Status',
    rec: 'ETHO Received in Collateral Address',
    sent: 'ETHO Sent from Collateral Address',
    noData: 'No Data.',
  },
  // About Component
  about: {
    version: 'Weergawe:',
    author: 'Skrywers:',
    funded: 'Befonds deur:',
    contact: 'Kontak Ons:',
    translators: 'Vertalers:',
  },
  // Cordova Component
  cordova: {
    signin: 'Meld aan',
    error_screenlock: 'Skakel asseblief die skermsluit op u toestel in. Hierdie app kan nie daarsonder werk nie.',
    error_sec_storage: "Die program kon nie veilige berging opstel nie weens 'n onbekende fout. Die app kan nie daarsonder werk nie.",
    title: 'Meld by u beursie aan met biometriese verifikasie',
    error_screenlock_changed: "Dit lyk of u die skermslot verander / verwyder het. Stel asseblief 'n skermslot op en installeer die app weer.",
  },
  // Nav Drawer component
  nav: {
    about: 'Oor',
    signout: 'Teken uit',
  },
  // Manin layout
  main: {
    cache: 'Data is nog nie gestoor nie. Probeer asb. Weer aanlyn.',
  },
  // 404 Page
  error_404: {
    sorry: 'Jammer, niks hier nie ...',
  },
  // Keystore
  keystore: {
    fail: "Kon nie 'n keystore skep nie, kontak ons ​​asseblief.",
    success: 'Keystore created successfully.',
    message: "Kopieer eenvoudig die gegenereerde keystore en plak dit in 'n lêer genaamd keystore.json - U kan dan u mobiele beursie op gebruik MyEtherWallet of MyCrypto. As u om u wagwoord gevra word, gebruik u die app-speld.",
  },
  // Home Page
  home: {
    balance: 'Walletbalans:',
    mcap: 'Markkapitalisasie:',
    volume: 'Deel (USD): $',
    mdata_error: 'Kan nie aangevraagde markdata ophaal nie',
    last_tx_in: 'Laaste TX in:',
    last_tx_out: 'Laaste TX uit:',
    receive: 'Ontvang',
    send: 'Stuur ',
    website: 'Ether-1 Webwerf',
    settings: 'Programinstellings',
    txs: 'transaksies',
    error_getting_txs: 'Kon nie transaksies ophaal nie',
    copied: 'Gekopieerde teks',
    not_signed_in: 'Please Sign in',
    markets_not_supported: 'Market Stats Not Supported on:',
    conv_not_supported: 'Price Conversion Not Supported on:',
    transactions_not_supported: 'TX Tracking is not available on:',
  },
  // User Index (Wallet Setup)
  index: {
    welcome: 'Welkom by die',
    name: 'Ether-1 Mobiele beursie !',
    before: "Voordat u begin, het ons 'n paar belangrike kennisgewings om eers deur te kom.",
    attention: 'Let asseblief op die volgende:',
    access: 'Ons het nie toegang tot u beursie nie.',
    reset: 'Ons kan nie u speld terugstel nie.',
    backup: 'Rugsteun u privaat sleutel.',
    client: 'U is verantwoordelik vir u beursie, die app is volledig kliëntekant en gebruik slegs ons RPC om transaksies uit te saai.',
    pin: 'As u u ID, PIN, gesig of aanraking deaktiveer, verloor u toegang tot u beursie en fondse, en u moet dus u privaat sleutel rugsteun.',
    understand: 'Ek Verstaan',
    setting: 'Ons is besig met die opstel van u',
    wallet: 'Ether-1 Wallet',
    address: 'Hieronder is u unieke beursie-adres:',
    pkey: 'Hieronder is u privaat sleutel:',
    backup_pkey: 'Onthou asseblief om u privaat sleutel te rugsteun!',
    got_it: 'Ek het dit!',
    set: 'Jy is reg, joune',
    ready: 'is gereed!',
    by: 'deur:',
    funded: 'befonds',
    developed: 'ontwikkel',
    the_wallet: 'Die Ether-1 Wallet was',
    secure: 'Beveilig my beursie',
    encrypt: 'Enkripteer u beursie:',
    wallet_name: 'Gebruikersnaam',
    use_pin: "Voer 'n unieke speld in",
    confirm: 'Bevestig u speld',
    required_name: "'N Wallet-naam word benodig",
    required_pin: "'N Speld is nodig",
    retype_pin: 'Tik asseblief u Pin weer om te bevestig',
    no_match: 'Die spelde wat voorsien word stem nie ooreen nie',
    weak_pin: "Die gekose pin is baie swak. Dit moet minstens 10 karakters lank wees en 'n nommer hê.",
    copied: 'Gekopieerde teks',
    language: 'Kies u voorkeurtaal:',
    unreg: 'Haai! Ons het opgemerk dat u rekening nie geregistreer is nie. Om toegang tot wolkkontakte te verkry en te gebruik, moet u u gebruikersnaam bevestig. Sodra u druk, kan u gebruikersnaam NIE verander word nie. Geen persoonlike inligting word in die wolk gestoor nie.',
  },
  // Receive Page
  receive: {
    scan: 'Skandeer die QR-kode om te ontvang',
    address: 'adres',
    warning: 'U kan slegs EVM coins na hierdie adres ontvang!',
    current_price: '-prys in',
    wallet_addr: 'Wallet-adres',
    copied: 'Gekopieerde teks',
  },
  // Send Page
  send: {
    recent: 'Onlangse:',
    no_recent: 'Geen onlangse oordragte nie',
    no_contacts: 'Geen kontakte bygevoeg nie',
    send_to: 'Hoeveel wil u stuur na',
    add_contact: 'Voeg kontak by',
    name: 'Naam:',
    address: 'Adres:',
    save: 'Save',
    delete: 'Vee kontak uit',
    copy_address: 'Gekopieerde Adres',
    invalid_address: 'Ongeldig Adres',
    not_pasted: 'Kan nie plak nie',
    cancelled_scan: 'Gekanselleerde skandering',
    unable_scan: 'Kan nie skandeer nie',
    scan_prompt: 'Skandeer adres QR-kode',
    contact_added: 'Kontak bygevoeg',
    enter_name: 'Voer naam in:',
    enter_address: 'Voer adres in:',
    exists: 'het reeds hierdie adres',
    copied: 'Gekopieerde Adres',
    sending: 'Oordrag van munte',
    app_error: 'Onverwagte fout. Installeer asseblief die program weer',
    tx_success: 'TRANSAKSIE VOLTOOI',
    tx_failed: 'TRANSAKSIE ONSUKSESVOL',
    online: 'Cloud Contact',
    no_online: 'Please search for a username, if none appear here, they do not exist in our database.',
    add: 'Download Contact',
  },
  // Settings Page
  settings: {
    node_stats: 'Node Stats:',
    chain_id: 'ChainID:',
    Blockheight: 'Current Blockheight:',
    version: 'Node Version:',
    sync_status: 'Sync Status:',
    app: 'Programinstellings',
    select_currency: 'Kies u valuta:',
    select_language: 'Kies u taal:',
    about: 'Oor Black Wallet:',
    about_etho: 'Oor Ether-1',
    error_offline: 'Op die regte pad',
    keystore: 'Genereer Keystore',
    about_black: 'About etho.black',
    about_ncr: 'About 3rd Party Developer (newCodeRunner)',
    stats: 'Ether-1 Network Stats',
    git: 'Ether-1 Github',
    select_network: 'Select Blockchain',
  },
  // SupportedCurrencies Page
  SupportedCurrencies: {
    changed: 'Currency Changed to: ',
  },
  // SupportedLanguages
  SupportedLanguages: {
    changed: 'Taal verander na: ',
  },
  // Transactions
  txs: {
    recent_txs: 'Onlangse oordragte',
    no_txs: 'Geen oordragte is in die laaste 1000 blokke gedoen nie.',
    retrieved: 'Teruggevorderde transaksies',
    error: 'Kon nie transaksies ophaal nie',
  },
  // Currency Symbols - Do Not Change.
  etho: 'ETHO',
  zar: 'R',
  usd: '$',
  eur: '€',
  ltc: 'Ł',
  btc: '₿',
  eth: 'Ξ',
  bch: 'BCH',
  bnb: 'BNB',
  eos: 'EOS',
  xrp: 'XRP',
  xlm: 'XLM',
  aed: 'د.إ',
  ars: '$',
  aud: '$',
  bdt: '৳',
  bhd: '.د.ب',
  bmd: '$',
  brl: 'R$',
  cad: '$',
  chf: 'Fr',
  clp: '$',
  cny: '¥',
  czk: 'Kč',
  dkk: 'Kr.',
  gbp: '£',
  hkd: '$',
  huf: 'Ft',
  idr: 'Rp',
  ils: '₪',
  inr: '₹',
  jpy: '¥',
  krw: '₩',
  kwd: 'د.ك',
  lkr: 'Rs',
  mmk: 'K',
  mxn: '$',
  myr: 'RM',
  nok: 'kr',
  nzd: '$',
  php: '₱',
  pkr: '₱',
  pln: 'zł',
  rub: '₽',
  sar: '﷼‎,',
  sek: 'kr',
  sgd: '$',
  thb: '฿',
  try: '₺',
  twd: '$',
  uah: '₴',
  vef: 'Bs.',
  vnd: '₫',
  xdr: 'SDR.',
  xag: 'XAG',
  xau: 'XAU',
};
