export default {
  lang: 'Afrikaans',
  failed: 'Aksie het misluk',
  success: 'Aksie was suksesvol',
  RPCCheck: 'Alle stelsels is aanlyn',
  RPCCheck_fail: "Dit blyk dat ons RPC tans nie gesinkroniseer is nie, saldo 's kan verkeerd wees en TX's sal nie werk nie.Funksionaliteit sal so gou moontlik herstel word.",
  // Routes
  routes: {
    config: 'Opset',
    settings: 'Instellings',
    send: 'Stuur',
    txs: 'Transaksies',
    receive: 'Ontvang',
    home: 'Huis',
    supcurr: 'Ondersteunde geldeenhede',
    suplang: 'Ondersteunde tale',
    keystore: 'Generate Keystore',
    supnet: 'Supported Networks',
  },
  // About Component
  about: {
    version: 'Weergawe:',
    author: 'Skrywers:',
    funded: 'Befonds deur:',
    contact: 'Kontak Ons:',
    translators: 'Vertalers:',
  },
  // Cordova Component
  cordova: {
    signin: 'Meld aan',
    error_screenlock: 'Skakel asseblief die skermsluit op u toestel in. Hierdie app kan nie daarsonder werk nie.',
    error_sec_storage: "Die program kon nie veilige berging opstel nie weens 'n onbekende fout. Die app kan nie daarsonder werk nie.",
    title: 'Meld by u beursie aan met biometriese verifikasie',
    error_screenlock_changed: "Dit lyk of u die skermslot verander / verwyder het. Stel asseblief 'n skermslot op en installeer die app weer.",
  },
  // Nav Drawer component
  nav: {
    about: 'Oor',
    signout: 'Teken uit',
  },
  // Manin layout
  main: {
    cache: 'Data is nog nie gestoor nie. Probeer asb. Weer aanlyn.',
  },
  // 404 Page
  error_404: {
    sorry: 'Jammer, niks hier nie ...',
  },
  // Keystore
  keystore: {
    fail: "Kon nie 'n keystore skep nie, kontak ons ​​asseblief.",
    success: 'Keystore created successfully.',
    message: "Kopieer eenvoudig die gegenereerde keystore en plak dit in 'n lêer genaamd keystore.json - U kan dan u mobiele beursie op gebruik MyEtherWallet of MyCrypto. As u om u wagwoord gevra word, gebruik u die app-speld.",
  },
  // Home Page
  home: {
    balance: 'Walletbalans:',
    mcap: 'Markkapitalisasie:',
    volume: 'Deel (USD): $',
    mdata_error: 'Kan nie aangevraagde markdata ophaal nie',
    last_tx_in: 'Laaste TX in:',
    last_tx_out: 'Laaste TX uit:',
    receive: 'Ontvang',
    send: 'Stuur ',
    website: 'Ether-1 Webwerf',
    settings: 'Programinstellings',
    txs: 'transaksies',
    error_getting_txs: 'Kon nie transaksies ophaal nie',
    copied: 'Gekopieerde teks',
    not_signed_in: 'Please Sign in',
    markets_not_supported: 'Market Stats Not Supported on:',
    conv_not_supported: 'Price Conversion Not Supported on:',
    transactions_not_supported: 'TX Tracking is not available on:',
  },
  // User Index (Wallet Setup)
  index: {
    welcome: 'Welkom by die',
    name: 'Ether-1 Mobiele beursie !',
    before: "Voordat u begin, het ons 'n paar belangrike kennisgewings om eers deur te kom.",
    attention: 'Let asseblief op die volgende:',
    access: 'Ons het nie toegang tot u beursie nie.',
    reset: 'Ons kan nie u speld terugstel nie.',
    backup: 'Rugsteun u privaat sleutel.',
    client: 'U is verantwoordelik vir u beursie, die app is volledig kliëntekant en gebruik slegs ons RPC om transaksies uit te saai.',
    pin: 'As u u ID, PIN, gesig of aanraking deaktiveer, verloor u toegang tot u beursie en fondse, en u moet dus u privaat sleutel rugsteun.',
    understand: 'Ek Verstaan',
    setting: 'Ons is besig met die opstel van u',
    wallet: 'Ether-1 Wallet',
    address: 'Hieronder is u unieke beursie-adres:',
    pkey: 'Hieronder is u privaat sleutel:',
    backup_pkey: 'Onthou asseblief om u privaat sleutel te rugsteun!',
    got_it: 'Ek het dit!',
    set: 'Jy is reg, joune',
    ready: 'is gereed!',
    by: 'deur:',
    funded: 'befonds',
    developed: 'ontwikkel',
    the_wallet: 'Die Ether-1 Wallet was',
    secure: 'Beveilig my beursie',
    encrypt: 'Enkripteer u beursie:',
    wallet_name: 'Gebruikersnaam',
    use_pin: "Voer 'n unieke speld in",
    confirm: 'Bevestig u speld',
    required_name: "'N Wallet-naam word benodig",
    required_pin: "'N Speld is nodig",
    retype_pin: 'Tik asseblief u Pin weer om te bevestig',
    no_match: 'Die spelde wat voorsien word stem nie ooreen nie',
    weak_pin: "Die gekose pin is baie swak. Dit moet minstens 10 karakters lank wees en 'n nommer hê.",
    copied: 'Gekopieerde teks',
    language: 'Kies u voorkeurtaal:',
    unreg: 'Haai! Ons het opgemerk dat u rekening nie geregistreer is nie. Om toegang tot wolkkontakte te verkry en te gebruik, moet u u gebruikersnaam bevestig. Sodra u druk, kan u gebruikersnaam NIE verander word nie. Geen persoonlike inligting word in die wolk gestoor nie.',
  },
  // Receive Page
  receive: {
    scan: 'Skandeer die QR-kode om te ontvang',
    address: 'adres',
    warning: 'U kan slegs EVM coins na hierdie adres ontvang!',
    current_price: '-prys in',
    wallet_addr: 'Wallet-adres',
    copied: 'Gekopieerde teks',
  },
  // Send Page
  send: {
    recent: 'Onlangse:',
    no_recent: 'Geen onlangse oordragte nie',
    no_contacts: 'Geen kontakte bygevoeg nie',
    send_to: 'Hoeveel wil u stuur na',
    add_contact: 'Voeg kontak by',
    name: 'Naam:',
    address: 'Adres:',
    save: 'Save',
    delete: 'Vee kontak uit',
    copy_address: 'Gekopieerde Adres',
    invalid_address: 'Ongeldig Adres',
    not_pasted: 'Kan nie plak nie',
    cancelled_scan: 'Gekanselleerde skandering',
    unable_scan: 'Kan nie skandeer nie',
    scan_prompt: 'Skandeer adres QR-kode',
    contact_added: 'Kontak bygevoeg',
    enter_name: 'Voer naam in:',
    enter_address: 'Voer adres in:',
    exists: 'het reeds hierdie adres',
    copied: 'Gekopieerde Adres',
    sending: 'Oordrag van munte',
    app_error: 'Onverwagte fout. Installeer asseblief die program weer',
    tx_success: 'TRANSAKSIE VOLTOOI',
    tx_failed: 'TRANSAKSIE ONSUKSESVOL',
    online: 'Cloud Contact',
    no_online: 'Please search for a username, if none appear here, they do not exist in our database.',
    add: 'Download Contact',
  },
  // Settings Page
  settings: {
    node_stats: 'Node Stats:',
    chain_id: 'ChainID:',
    Blockheight: 'Current Blockheight:',
    version: 'Node Version:',
    sync_status: 'Sync Status:',
    app: 'Programinstellings',
    select_currency: 'Kies u valuta:',
    select_language: 'Kies u taal:',
    about: 'Oor Black Wallet:',
    about_etho: 'Oor Ether-1',
    error_offline: 'Op die regte pad',
    keystore: 'Genereer Keystore',
    about_black: 'About etho.black',
    about_ncr: 'About 3rd Party Developer (newCodeRunner)',
    stats: 'Ether-1 Network Stats',
    git: 'Ether-1 Github',
    select_network: 'Select Blockchain',
  },
  // SupportedCurrencies Page
  SupportedCurrencies: {
    changed: 'Currency Changed to: ',
  },
  // SupportedLanguages
  SupportedLanguages: {
    changed: 'Taal verander na: ',
  },
  // Transactions
  txs: {
    recent_txs: 'Onlangse oordragte',
    no_txs: 'Geen oordragte is in die laaste 1000 blokke gedoen nie.',
    retrieved: 'Teruggevorderde transaksies',
    error: 'Kon nie transaksies ophaal nie',
  },
  // Currency Symbols - Do Not Change.
  etho: 'ETHO',
  zar: 'R',
  usd: '$',
  eur: '€',
  ltc: 'Ł',
  btc: '₿',
  eth: 'Ξ',
  bch: 'BCH',
  bnb: 'BNB',
  eos: 'EOS',
  xrp: 'XRP',
  xlm: 'XLM',
  aed: 'د.إ',
  ars: '$',
  aud: '$',
  bdt: '৳',
  bhd: '.د.ب',
  bmd: '$',
  brl: 'R$',
  cad: '$',
  chf: 'Fr',
  clp: '$',
  cny: '¥',
  czk: 'Kč',
  dkk: 'Kr.',
  gbp: '£',
  hkd: '$',
  huf: 'Ft',
  idr: 'Rp',
  ils: '₪',
  inr: '₹',
  jpy: '¥',
  krw: '₩',
  kwd: 'د.ك',
  lkr: 'Rs',
  mmk: 'K',
  mxn: '$',
  myr: 'RM',
  nok: 'kr',
  nzd: '$',
  php: '₱',
  pkr: '₱',
  pln: 'zł',
  rub: '₽',
  sar: '﷼‎,',
  sek: 'kr',
  sgd: '$',
  thb: '฿',
  try: '₺',
  twd: '$',
  uah: '₴',
  vef: 'Bs.',
  vnd: '₫',
  xdr: 'SDR.',
  xag: 'XAG',
  xau: 'XAU',
};
