export default {
  lang: 'Spanish',
  failed: 'Acción fallida',
  success: 'Acción exitosa',
  RPCCheck: 'Todos los sistemas están en línea',
  RPCCheck_fail: 'Parece que nuestro RPC actualmente no está sincronizado, los saldos pueden ser incorrectos y los TX no funcionarán, la funcionalidad se restaurará lo antes posible.',
  // Routes
  routes: {
    config: 'Configuración',
    settings: 'Ajustes',
    send: 'Enviar',
    txs: 'Transacciones',
    receive: 'Recibir',
    home: 'Home',
    supcurr: 'Monedas',
    suplang: 'Idiomas',
    keystore: 'Exportar llave',
    supnet: 'Redes',
  },
  // About Component
  about: {
    version: 'Version:',
    author: 'Autores:',
    funded: 'Fundado por:',
    contact: 'Contáctanos:',
    translators: 'Traductores:',
  },
  // Cordova Component
  cordova: {
    signin: 'Registrarse',
    error_screenlock: 'Active el bloqueo de pantalla en su dispositivo. Esta aplicación no puede funcionar sin ella.',
    error_sec_storage: 'La aplicación no pudo configurar el almacenamiento seguro debido a un error desconocido. La aplicación no puede funcionar sin él.',
    title: 'Inicie sesión en su billetera con autenticación biométrica',
    error_screenlock_changed: 'Parece que cambió / eliminó el bloqueo de pantalla. Configure un bloqueo de pantalla y vuelva a instalar la aplicación.',
  },
  // Nav Drawer component
  nav: {
    about: 'Acerca de',
    signout: 'Desconectar',
  },
  // Manin layout
  main: {
    cache: 'Los datos aún no se han almacenado en caché. Vuelva a intentarlo cuando esté en línea',
  },
  // 404 Page
  error_404: {
    sorry: 'Lo siento, no hay nada aquí...',
  },
  // Keystore
  keystore: {
    fail: 'No se pudo generar un almacén de claves, por favor contáctenos.',
    success: 'El almacén de claves se creó correctamente.',
    message: 'Simplemente copie el almacén de claves generado y péguelo en un archivo llamado keystore.json; luego puede usar su billetera móvil en MyEtherWallet o MyCrypto. Cuando se le solicite su contraseña, utilice el pin de su aplicación.',
  },
  // Home Page
  home: {
    balance: 'Saldo',
    mcap: 'Capitalización:',
    volume: 'Volume (USD): $',
    mdata_error: 'No se pueden recuperar los datos solicitados',
    last_tx_in: 'Última transacción recibida:',
    last_tx_out: 'Última transacción enviada:',
    receive: 'Recibir',
    send: 'Enviar',
    website: 'Ether-1 Website',
    settings: 'Ajustes de la Aplicación',
    txs: 'Transacciones',
    error_getting_txs: 'Error al recuperar las transacciones',
    copied: 'Texto copiado',
    not_signed_in: 'Por favor, registrese',
    markets_not_supported: 'Estadísticas de mercado no admitidas en:',
    conv_not_supported: 'Conversión de precio no admitida en:',
    transactions_not_supported: 'La transacción no está disponible en:',
  },
  // User Index (Wallet Setup)
  index: {
    welcome: 'Bievenidos a',
    name: 'Billetera Móvil Ether-1 !',
    before: 'Antes de comenzar, tenemos algunos avisos importantes que debemos revisar primero.',
    attention: 'Por favor preste mucha atención a lo siguiente:',
    access: 'Nosotros no podemos acceder a su billetera.',
    reset: 'Nosotros no podemos restablecer su código PIN.',
    backup: 'Haga una copia de seguridad de su clave privada.',
    client: 'Usted es responsable de su billetera, la aplicación es completamente del lado del cliente y solo usa nuestro RPC para transmitir transacciones.',
    pin: "Si deshabilita el Pin, Face o Touch ID de su teléfono, perderá el acceso a su billetera y fondos, por eso debe hacer una copia de seguridad de su clave privada.",
    understand: 'Entiendo',
    setting: "Estamos ocupados configurando su",
    wallet: 'Billetera Ether-1',
    address: 'Esta es su dirección de billetera única:',
    pkey: 'A continuación se muestra su clave privada:',
    backup_pkey: 'Recuerde respaldar su clave privada!',
    got_it: "¡Entendido!!",
    set: "You're all set, your",
    ready: 'estas listo!',
    by: 'por:',
    funded: 'fundado',
    developed: 'desarrollado',
    the_wallet: 'La billetera Ether-1 fue',
    secure: 'Asegurar mi billetera',
    encrypt: 'Encriptar mi billetera:',
    wallet_name: 'Nombre de usuario',
    use_pin: 'Ingrese una clave PIN',
    confirm: 'Confirmar PIN',
    required_name: 'Se requiere un nombre de billetera',
    required_pin: 'Se requiere PIN',
    retype_pin: 'Vuelva a escribir su PIN para confirmar',
    no_match: 'Los PIN no coinciden',
    weak_pin: 'El PIN elegido es muy débil. Debe tener al menos 10 caracteres y tener un número.',
    copied: 'Texto Copiado',
    language: 'Seleccione su idioma preferido:',
    unreg: '¡Oye! Hemos notado que su cuenta no está registrada. Para acceder y utilizar los contactos en la nube, le solicitamos que confirme su nombre de usuario. Una vez que presione confirmar, su nombre de usuario NO PUEDE cambiarse. No se almacena información personal en la nube.! We have noticed that your account is unregistered. In order to access & use cloud contacts we require you to confirm your Username. Once you press confirm your username CANNOT be changed. No personal information is stored in the cloud.',
  },
  // Receive Page
  receive: {
    scan: 'Escanee el código QR para recibir',
    address: 'Dirección',
    warning: '¡Solo puedes recibir monedas EVM en esta dirección!',
    current_price: 'Precio en',
    wallet_addr: 'Dirección de Billetera',
    copied: 'Texto Copiado',
  },
  // Send Page
  send: {
    recent: 'Reciente:',
    no_recent: 'No hay transferencias recientes',
    no_contacts: 'No se agregaron contactos',
    send_to: 'A cuántos quieres enviar',
    add_contact: 'Agregar Contacto',
    name: 'Nombre:',
    address: 'Dirección:',
    save: 'Salvar',
    delete: 'Borrar Contacto',
    copy_address: 'Copiar Dirección',
    invalid_address: 'Dirección Invalida',
    not_pasted: 'No se puede pegar',
    cancelled_scan: 'Escaneo Cancelado',
    unable_scan: 'No se puede escanear',
    scan_prompt: 'Escanear código QR',
    contact_added: 'Contacto Agregado',
    enter_name: 'Ingresar Nombre:',
    enter_address: 'Ingresar Dirección:',
    exists: 'La Dirección ya existe',
    copied: 'Dirección Copiada',
    sending: 'Enviando Monedas',
    app_error: 'Error inesperado, reinstale la aplicación',
    tx_success: 'TRANSACCIÓN COMPLETADA',
    tx_failed: 'TRANSACCIÓN FALLIDA',
    online: 'Contacto en la Nube',
    no_online: 'Por favor busque un nombre de usuario, si ninguno aparece aquí, no existe en nuestra base de datos.',
    add: 'Descargar Contacto',
  },
  // Settings Page
  settings: {
    node_stats: 'Estadísticas de Nodo:',
    chain_id: 'ChainID:',
    Blockheight: 'Blockheigh actual:',
    version: 'Versión de Nodo:',
    sync_status: 'Estado de Sincronización:',
    app: 'Configuración de la Aplicación',
    select_currency: 'Seleccione su moneda preferida:',
    select_language: 'Seleccione su lenguaje preferido:',
    about: 'Acerca de Black Wallet:',
    about_etho: 'About Ether-1',
    error_offline: 'Sin conexión',
    keystore: 'Generar almacén de claves',
    about_black: 'Acerca de etho.black',
    about_ncr: 'Acercar del Desarrolador Externo (newCodeRunner)',
    stats: 'Estadisticas de Red Ether-1',
    git: 'Ether-1 Github',
    select_network: 'Seleccionar Blockchain',
  },
  // SupportedCurrencies Page
  SupportedCurrencies: {
    changed: 'Cambiar Moneda: ',
  },
  // SupportedLanguages
  SupportedLanguages: {
    changed: 'Cambiar Lenguaje: ',
  },
  // Transactions
  txs: {
    recent_txs: 'Transferencias recientes',
    no_txs: 'No se realizaron transferencias en los últimos 1000 bloques.',
    retrieved: 'Transacciones recuperadas',
    error: 'Error al recuperar transacciones',
  },
  // Currency Symbols - Do Not Change.
  etho: 'ETHO',
  zar: 'R',
  usd: '$',
  eur: '€',
  ltc: 'Ł',
  btc: '₿',
  eth: 'Ξ',
  bch: 'BCH',
  bnb: 'BNB',
  eos: 'EOS',
  xrp: 'XRP',
  xlm: 'XLM',
  aed: 'د.إ',
  ars: '$',
  aud: '$',
  bdt: '৳',
  bhd: '.د.ب',
  bmd: '$',
  brl: 'R$',
  cad: '$',
  chf: 'Fr',
  clp: '$',
  cny: '¥',
  czk: 'Kč',
  dkk: 'Kr.',
  gbp: '£',
  hkd: '$',
  huf: 'Ft',
  idr: 'Rp',
  ils: '₪',
  inr: '₹',
  jpy: '¥',
  krw: '₩',
  kwd: 'د.ك',
  lkr: 'Rs',
  mmk: 'K',
  mxn: '$',
  myr: 'RM',
  nok: 'kr',
  nzd: '$',
  php: '₱',
  pkr: '₱',
  pln: 'zł',
  rub: '₽',
  sar: '﷼‎,',
  sek: 'kr',
  sgd: '$',
  thb: '฿',
  try: '₺',
  twd: '$',
  uah: '₴',
  vef: 'Bs.',
  vnd: '₫',
  xdr: 'SDR.',
  xag: 'XAG',
  xau: 'XAU',
};
