export default {
  lang: 'Dutch',
  failed: 'Actie mislukt',
  success: 'Actie succesvol',
  RPCCheck: 'Alle systemen zijn online',
  RPCCheck_fail: "Het lijkt erop dat onze RPC momenteel niet gesynchroniseerd is, saldi kunnen onjuist zijn en TX's zullen niet werken.De functionaliteit wordt zo snel mogelijk hersteld.",
  // Routes
  routes: {
    config: 'Configuratie',
    settings: 'Instellingen',
    send: 'Verstuur',
    txs: 'Transacties',
    receive: 'Ontvang',
    home: 'Thuis',
    supcurr: 'Beschikbare Currencies',
    suplang: 'Beschikbare Talen',
    keystore: 'Exporteer Sleutel',
    supnet: 'Supported Networks',
  },
  lending_dapp: {
    accept: 'Accept',
    decline: 'Decline',
    beta: 'Mobile Beta',
    myContracts: 'My Contracts',
    toRemove: "If you'd like to remove a contract, simply press on the contract.",
    type: 'Type',
    available: 'Available',
    noContractsOrLoading: 'No Contracts found OR Data is Loading...',
    welcome: 'Welcome to the Ether-1 Lending Dapp',
    desc: `The Ether-1 node staking dashboard provides ETHO stake holders and node
    operators a chance to come together and profit from an Ether-1 node,
    providing a valuable service to the Ether-1 & ethoFS networks, all while
    remaining completely decentralized in nature.`,
    desc_expanded: `Our staking is unique because it doesn’t increase ETHO inflation and it
    not only locks up coins, it also provides more fully operational
    Ether-1/ethoFS nodes to make our community data swarm even greater.`,
    termsHeading: 'Terms of Agreement',
    term1: `Borrower and Lender both agree they understand and consent to the
    terms and conditions below upon entering their private keys on
    this website.`,
    term2: `After claiming an available staking contract, Borrower has 50,000
    blocks to setup an active and paying Ether-1 node using Lender's
    smart contract stake. Failure to do so gives Lender the option to
    collect Borrower's origination fee.`,
    term3: `When Borrower's Ether-1 node produces its first reward payment
    within 50,000 blocks, contract status is changed from inactive to
    active. The contract status is changed back to inactive if the
    Borrower's node loses its paying status for a single payment
    period. Lender has the option to reset/remove an inactive contract
    between 50,000 and 199,999 blocks and collect Borrower’s
    origination fee.`,
    term4: `Lender can reset/remove an active contract after 200,000 blocks
    with the origination fee returned to the Borrower. Borrower can
    abandon an active contract after 200,000 blocks with the
    origination fee returned to the Borrower.`,
    term5: `If Borrower abandons an active contract within the first 200,000
    blocks, security deposit is forfeited to the Lender.`,
    term6: `Lender can cancel an active contract only after 200,000 blocks,
    with 95% of the origination fee returned to the Borrower.`,
    notes: 'NOTES',
    note1: `Lender has the option to stipulate additional Terms and Conditions
    within each staking contract. By claiming the staking contract,
    Borrower agrees to Lender's additional Term and Conditions.`,
    note2: `Lender's additional stipulated Terms and Conditions do not
    supersede Smart Contract rules (1) through (6) listed above.`,
    nodeTypeAndSpilt: 'Select Node Type & Select Lender Split',
    create: 'Create A Lending Contract',
    get: 'Get Contracts',
    select: 'Select Node Type',
    split: 'Select Desired Lender Split %',
    fee: 'Select Desired Origination Fee',
    addTCs: 'Enter Addition Terms & Conditions',
    badNetwork: 'Incorrect Network',
    badDesc: 'Please Connect to the Ether-1 Network, if you wish to access the Staking dApp.',
    success: 'Success!',
    smsg: 'Your Lending Contract has been add to the staking platform.',
    error: 'ERROR',
    emsg1: 'You do NOT have enough balance to deploy this stake. You currently have',
    emsg2: 'ETHO, You need a total of',
    removedmsg: 'Your Lending Contract has been removed from the staking platform.',
  },
  nodes: {
    active: 'Active',
    stats: 'Node Stats',
    rewards: 'Last Reward for',
    owned: 'Owned Node Type',
    balance: 'Collateral Balance',
    status: 'Node Status',
    rec: 'ETHO Received in Collateral Address',
    sent: 'ETHO Sent from Collateral Address',
    noData: 'No Data.',
  },
  // About Component
  about: {
    version: 'Versie:',
    author: 'Autheurs:',
    funded: 'Gefinancierd Door:',
    contact: 'Contacteer Ons:',
    translators: 'Vertalers:',
  },
  // Cordova Component
  cordova: {
    signin: 'Log in',
    error_screenlock: 'Schakel de schermvergrendeling in op uw apparaat. Indien dit niet geactiveerd is kan deze app niet werken',
    error_sec_storage: 'De App kon geen veilige opslag instellen vanwege een onbekende fout.',
    title: 'Log in op uw portemonnee met biometrische authenticatie',
    error_screenlock_changed: 'Het lijkt erop dat je de schermvergrendeling hebt gewijzigd / verwijderd. Stel een schermvergrendeling in en installeer de app opnieuw.',
  },
  // Nav Drawer component
  nav: {
    about: 'Over',
    signout: 'Log Uit',
  },
  // Manin layout
  main: {
    cache: 'Data niet synchroon. Probeer het opnieuw als u online bent',
  },
  // 404 Page
  error_404: {
    sorry: 'Sorry, niets hier..',
  },
  // Keystore
  keystore: {
    fail: 'Kan geen keystore genereren, neem contact met ons op.',
    success: 'Keystore is succesvol aangemaakt.',
    message: 'Kopieer simpelweg de gegenereerde keystore en plak deze in een bestand met de naam keystore.json - U kunt dan uw mobiele portemonnee gebruiken op MyEtherWallet of MyCrypto. Wanneer u om uw wachtwoord wordt gevraagd, gebruikt u uw app-pincode.',
  },
  // Home Page
  home: {
    balance: 'Portfolio',
    mcap: 'Markt Kapitalisatie:',
    volume: 'Volume (USD): $',
    mdata_error: 'Kan gevraagde marktgegevens niet ophalen',
    last_tx_in: 'Laatste TX in:',
    last_tx_out: 'Laatste TX out:',
    receive: 'Ontvang',
    send: 'Verstuur',
    website: 'Ether-1 Website',
    settings: 'App Instellingen',
    txs: 'Transacties',
    error_getting_txs: 'Error Opvragen Transacties',
    copied: 'Tekst gekopieerd',
    not_signed_in: 'Please Sign in',
    markets_not_supported: 'Market Stats Not Supported on:',
    conv_not_supported: 'Price Conversion Not Supported on:',
    transactions_not_supported: 'TX Tracking is not available on:',
  },
  // User Index (Wallet Setup)
  index: {
    welcome: 'Welkom op de',
    name: 'Ether-1 Mobile Wallet !',
    before: 'Vooraleer u de app kan gebruiken moet u met het onderstaande rekening houden.',
    attention: 'Hou alstublieft rekening met het volgende:',
    access: 'Wij hebben geen toegang tot uw portomonnee.',
    reset: 'Wij kunnen je wachtwoord/pincode niet wijzigen.',
    backup: 'Maak een reservekopie van uw portomonnee.',
    client: 'U bent verantwoordelijk voor je portemonnee, de app is volledig lokaal en gebruikt onze RPC alleen om transacties uit te zenden.',
    pin: 'Als u de Pin, Face of Touch ID van uw telefoon uitschakelt, verliest u de toegang tot uw portemonnee en uw geld, daarom moet u een zeker en vast back-up van uw privésleutel maken.',
    understand: 'Ik begrijp het',
    setting: 'We zijn bezig met het instellen van uw',
    wallet: 'Ether-1 Wallet',
    address: 'Hieronder vindt u uw unieke portefeuilleadres:',
    pkey: 'Hieronder vindt u uw privésleutel:',
    backup_pkey: 'Vergeet niet om een back-up te maken van uw privésleutel!',
    got_it: 'Hebbes!',
    set: 'U bent helemaal klaar!',
    ready: 'is klaar!',
    by: 'door:',
    funded: 'gefinancierd',
    developed: 'ontwikkeld',
    the_wallet: 'De Ether-1 Wallet was',
    secure: 'Beveilig mijn portomonnee',
    encrypt: 'Versleutel mijn portomonnee:',
    wallet_name: 'Gebruikersnaam',
    use_pin: 'Voer een unieke code in',
    confirm: 'Bevestig uw code',
    required_name: 'Gelieve je portomonnee een naam te geven',
    required_pin: 'Gelieve een pincode te kiezen',
    retype_pin: 'Voer uw pincode nogmaals in',
    no_match: 'De pincode komt niet overeen',
    weak_pin: 'De gekozen pincode is zeer zwak. Gelieve minstens 10 karakters te gebruiken waaronder 1 cijfer.',
    copied: 'Tekst gekopierd',
    language: 'Please select your preferred language:',
    unreg: 'Hallo! We hebben gemerkt dat uw account niet is geregistreerd. Om toegang te krijgen tot en gebruik te maken van cloudcontacten, moet u uw gebruikersnaam bevestigen. Zodra u op bevestigt, kan uw gebruikersnaam NIET worden gewijzigd. Er wordt geen persoonlijke informatie opgeslagen in de cloud.',
  },
  // Receive Page
  receive: {
    scan: 'Scan de QR-code om te ontvangen',
    address: 'Adres',
    warning: 'U kunt EVM coins alleen op dit adres ontvangen!',
    current_price: 'Prijs in',
    wallet_addr: 'Portomonnee adres',
    copied: 'Tekst gekopierd',
  },
  // Send Page
  send: {
    recent: 'Recente:',
    no_recent: 'Geen Recente Transacties',
    no_contacts: 'Geen contacten',
    send_to: 'Hoeveel wenst u te versturen',
    add_contact: 'Voeg contactpersoon toe',
    name: 'Naam:',
    address: 'Adres:',
    save: 'Opslaan',
    delete: 'Verwijder Contactpersoon',
    copy_address: 'Kopieer Adres',
    invalid_address: 'Foutief Adres',
    not_pasted: 'Plakken niet mogelijk',
    cancelled_scan: 'Scan onderbroken',
    unable_scan: 'Scan mislukt',
    scan_prompt: 'Scan Ares QR Code',
    contact_added: 'Contactpersoon Toegevoegd',
    enter_name: 'Voer naam in:',
    enter_address: 'Voer adres in:',
    exists: 'adres bestaat al',
    copied: 'Kopieer Adres',
    sending: 'Munten versturen',
    app_error: 'Onverwachte Error, Installeer de app opnieuw',
    tx_success: 'TRANSACTION SUCCESVOL',
    tx_failed: 'TRANSACTION MISLUKT',
    online: 'Cloud Contact',
    no_online: 'Please search for a username, if none appear here, they do not exist in our database.',
    add: 'Download Contact',
  },
  // Settings Page
  settings: {
    node_stats: 'Status van de Node:',
    chain_id: 'ChainID:',
    Blockheight: 'Momentele Blokhoogte:',
    version: 'Node Versie:',
    sync_status: 'Sync Status:',
    app: 'App Instellingen',
    select_currency: 'SELECTEER MUNTEENHEID:',
    select_language: 'SELECTEER TAAL:',
    about: 'Over Black Wallet:',
    about_etho: 'Over Ether-1:',
    error_offline: 'Offline',
    keystore: 'GENEREER KEYSTORE',
    about_black: 'Over etho.black',
    about_ncr: 'Over 3de Partij Ontwikkelaar (newCodeRunner)',
    stats: 'Ether-1 Netwerk Status',
    git: 'Ether-1 Github',
    select_network: 'Select Blockchain',
  },
  // SupportedCurrencies Page
  SupportedCurrencies: {
    changed: 'Munteenheid Verandert naar: ',
  },
  // SupportedLanguages
  SupportedLanguages: {
    changed: 'Taal Verandert naar: ',
  },
  // Transactions
  txs: {
    recent_txs: 'Recente Transacties',
    no_txs: 'Geen Transacties gemaakt in de laatste 1000 Blokken.',
    retrieved: 'Ontvangen transactions',
    error: 'Fout Bij Ontvangen Van Transacties',
  },
  // Currency Symbols - Do Not Change.
  etho: 'ETHO',
  zar: 'R',
  usd: '$',
  eur: '€',
  ltc: 'Ł',
  btc: '₿',
  eth: 'Ξ',
  bch: 'BCH',
  bnb: 'BNB',
  eos: 'EOS',
  xrp: 'XRP',
  xlm: 'XLM',
  aed: 'د.إ',
  ars: '$',
  aud: '$',
  bdt: '৳',
  bhd: '.د.ب',
  bmd: '$',
  brl: 'R$',
  cad: '$',
  chf: 'Fr',
  clp: '$',
  cny: '¥',
  czk: 'Kč',
  dkk: 'Kr.',
  gbp: '£',
  hkd: '$',
  huf: 'Ft',
  idr: 'Rp',
  ils: '₪',
  inr: '₹',
  jpy: '¥',
  krw: '₩',
  kwd: 'د.ك',
  lkr: 'Rs',
  mmk: 'K',
  mxn: '$',
  myr: 'RM',
  nok: 'kr',
  nzd: '$',
  php: '₱',
  pkr: '₱',
  pln: 'zł',
  rub: '₽',
  sar: '﷼‎,',
  sek: 'kr',
  sgd: '$',
  thb: '฿',
  try: '₺',
  twd: '$',
  uah: '₴',
  vef: 'Bs.',
  vnd: '₫',
  xdr: 'SDR.',
  xag: 'XAG',
  xau: 'XAU',
};
