export default {
    lang: 'Dutch',
    failed: 'Actie mislukt',
    success: 'Actie succesvol',
    RPCCheck: 'Alle systemen zijn online',
    RPCCheck_fail: "Het lijkt erop dat onze RPC momenteel niet gesynchroniseerd is, saldi kunnen onjuist zijn en TX's zullen niet werken.De functionaliteit wordt zo snel mogelijk hersteld.",
    // Routes
    routes: {
        config: 'Configuratie',
        settings: 'Instellingen',
        send: 'Verstuur',
        txs: 'Transacties',
        receive: 'Ontvang',
        home: 'Thuis',
        supcurr: 'Beschikbare Currencies',
        suplang: 'Beschikbare Talen',
        keystore: 'Exporteer Sleutel',
    },
    // About Component
    about: {
        version: 'Versie:',
        author: 'Autheurs:',
        funded: 'Gefinancierd Door:',
        contact: 'Contacteer Ons:',
        translators: 'Vertalers:',
    },
    // Cordova Component
    cordova: {
        signin: 'Log in',
        error_screenlock: 'Schakel de schermvergrendeling in op uw apparaat. Indien dit niet geactiveerd is kan deze app niet werken',
        error_sec_storage: 'De App kon geen veilige opslag instellen vanwege een onbekende fout.',
        title: 'Log in op uw portemonnee met biometrische authenticatie',
        error_screenlock_changed: 'Het lijkt erop dat je de schermvergrendeling hebt gewijzigd / verwijderd. Stel een schermvergrendeling in en installeer de app opnieuw.',
    },
    // Nav Drawer component
    nav: {
        about: 'Over',
        signout: 'Log Uit',
    },
    // Manin layout
    main: {
        cache: 'Data niet synchroon. Probeer het opnieuw als u online bent',
    },
    // 404 Page
    error_404: {
        sorry: 'Sorry, niets hier..',
    },
    // Keystore
    keystore: {
        fail: 'Kan geen keystore genereren, neem contact met ons op.',
        success: 'Keystore is succesvol aangemaakt.',
        message: 'Kopieer simpelweg de gegenereerde keystore en plak deze in een bestand met de naam keystore.json - U kunt dan uw mobiele portemonnee gebruiken op MyEtherWallet of MyCrypto. Wanneer u om uw wachtwoord wordt gevraagd, gebruikt u uw app-pincode.',
    },
    // Home Page
    home: {
        balance: 'Portfolio',
        mcap: 'Markt Kapitalisatie:',
        volume: 'Volume (USD): $',
        mdata_error: 'Kan gevraagde marktgegevens niet ophalen',
        last_tx_in: 'Laatste TX in:',
        last_tx_out: 'Laatste TX out:',
        receive: 'Ontvang ETHO',
        send: 'Verstuur ETHO',
        website: 'Ether-1 Website',
        settings: 'App Instellingen',
        txs: 'Transacties',
        error_getting_txs: 'Error Opvragen Transacties',
        copied: 'Tekst gekopieerd',
    },
    // User Index (Wallet Setup)
    index: {
        welcome: 'Welkom op de',
        name: 'Ether-1 Mobile Wallet !',
        before: 'Vooraleer u de app kan gebruiken moet u met het onderstaande rekening houden.',
        attention: 'Hou alstublieft rekening met het volgende:',
        access: 'Wij hebben geen toegang tot uw portomonnee.',
        reset: 'Wij kunnen je wachtwoord/pincode niet wijzigen.',
        backup: 'Maak een reservekopie van uw portomonnee.',
        client: 'U bent verantwoordelijk voor je portemonnee, de app is volledig lokaal en gebruikt onze RPC alleen om transacties uit te zenden.',
        pin: 'Als u de Pin, Face of Touch ID van uw telefoon uitschakelt, verliest u de toegang tot uw portemonnee en uw geld, daarom moet u een zeker en vast back-up van uw privésleutel maken.',
        understand: 'Ik begrijp het',
        setting: 'We zijn bezig met het instellen van uw',
        wallet: 'Ether-1 Wallet',
        address: 'Hieronder vindt u uw unieke portefeuilleadres:',
        pkey: 'Hieronder vindt u uw privésleutel:',
        backup_pkey: 'Vergeet niet om een back-up te maken van uw privésleutel!',
        got_it: 'Hebbes!',
        set: 'U bent helemaal klaar!',
        ready: 'is klaar!',
        by: 'door:',
        funded: 'gefinancierd',
        developed: 'ontwikkeld',
        the_wallet: 'De Ether-1 Wallet was',
        secure: 'Beveilig mijn portomonnee',
        encrypt: 'Versleutel mijn portomonnee:',
        wallet_name: 'Portemonnee naam',
        use_pin: 'Voer een unieke code in',
        confirm: 'Bevestig uw code',
        required_name: 'Gelieve je portomonnee een naam te geven',
        required_pin: 'Gelieve een pincode te kiezen',
        retype_pin: 'Voer uw pincode nogmaals in',
        no_match: 'De pincode komt niet overeen',
        weak_pin: 'De gekozen pincode is zeer zwak. Gelieve minstens 10 karakters te gebruiken waaronder 1 cijfer.',
        copied: 'Tekst gekopierd',
        language: 'Please select your preferred language:',
    },
    // Receive Page
    receive: {
        scan: 'Scan de QR-code om te ontvangen',
        address: 'ETHO Adres',
        warning: 'U kunt ETHO alleen op dit adres ontvangen!',
        current_price: 'ETHO Prijs in',
        wallet_addr: 'Portomonnee adres',
        copied: 'Tekst gekopierd',
    },
    // Send Page
    send: {
        recent: 'Recente:',
        no_recent: 'Geen Recente Transacties',
        no_contacts: 'Geen contacten',
        send_to: 'Hoeveel wenst u te versturen',
        add_contact: 'Voeg contactpersoon toe',
        name: 'Naam:',
        address: 'Adres:',
        save: 'Opslaan',
        delete: 'Verwijder Contactpersoon',
        copy_address: 'Kopieer Adres',
        invalid_address: 'Foutief Adres',
        not_pasted: 'Plakken niet mogelijk',
        cancelled_scan: 'Scan onderbroken',
        unable_scan: 'Scan mislukt',
        scan_prompt: 'Scan Ares QR Code',
        contact_added: 'Contactpersoon Toegevoegd',
        enter_name: 'Voer naam in:',
        enter_address: 'Voer adres in:',
        exists: 'adres bestaat al',
        copied: 'Kopieer Adres',
        sending: 'Munten versturen',
        app_error: 'Onverwachte Error, Installeer de app opnieuw',
        tx_success: 'TRANSACTION SUCCESVOL',
        tx_failed: 'TRANSACTION MISLUKT',
    },
    // Settings Page
    settings: {
        node_stats: 'Status van de Node:',
        chain_id: 'ChainID:',
        Blockheight: 'Momentele Blokhoogte:',
        version: 'Node Versie:',
        sync_status: 'Sync Status:',
        app: 'App Instellingen',
        select_currency: 'SELECTEER MUNTEENHEID:',
        select_language: 'SELECTEER TAAL:',
        about: 'Over Black Wallet:',
        about_etho: 'Over Ether-1:',
        error_offline: 'Offline',
        keystore: 'GENEREER KEYSTORE',
        about_black: 'Over etho.black',
        about_ncr: 'Over 3de Partij Ontwikkelaar (newCodeRunner)',
        stats: 'Ether-1 Netwerk Status',
        git: 'Ether-1 Github',
    },
    // SupportedCurrencies Page
    SupportedCurrencies: {
        changed: 'Munteenheid Verandert naar: ',
    },
    // SupportedLanguages
    SupportedLanguages: {
        changed: 'Taal Verandert naar: ',
    },
    // Transactions
    txs: {
        recent_txs: 'Recente Transacties',
        no_txs: 'Geen Transacties gemaakt in de laatste 1000 Blokken.',
        retrieved: 'Ontvangen transactions',
        error: 'Fout Bij Ontvangen Van Transacties',
    },
    // Currency Symbols - Do Not Change.
    etho: 'ETHO',
    zar: 'R',
    usd: '$',
    eur: '€',
    ltc: 'Ł',
    btc: '₿',
    eth: 'Ξ',
    bch: 'BCH',
    bnb: 'BNB',
    eos: 'EOS',
    xrp: 'XRP',
    xlm: 'XLM',
    aed: 'د.إ',
    ars: '$',
    aud: '$',
    bdt: '৳',
    bhd: '.د.ب',
    bmd: '$',
    brl: 'R$',
    cad: '$',
    chf: 'Fr',
    clp: '$',
    cny: '¥',
    czk: 'Kč',
    dkk: 'Kr.',
    gbp: '£',
    hkd: '$',
    huf: 'Ft',
    idr: 'Rp',
    ils: '₪',
    inr: '₹',
    jpy: '¥',
    krw: '₩',
    kwd: 'د.ك',
    lkr: 'Rs',
    mmk: 'K',
    mxn: '$',
    myr: 'RM',
    nok: 'kr',
    nzd: '$',
    php: '₱',
    pkr: '₱',
    pln: 'zł',
    rub: '₽',
    sar: '﷼‎,',
    sek: 'kr',
    sgd: '$',
    thb: '฿',
    try: '₺',
    twd: '$',
    uah: '₴',
    vef: 'Bs.',
    vnd: '₫',
    xdr: 'SDR.',
    xag: 'XAG',
    xau: 'XAU',
};
