export default {
  lang: 'French',
  failed: 'Action échoué',
  success: 'Action réussi',
  RPCCheck: 'Tous les systèmes sont en ligne',
  RPCCheck_fail: 'Il semble que notre RPC soit actuellement désynchronisé, les soldes peuvent être incorrects et les TX ne fonctionneront pas.La fonctionnalité sera rétablie dès que possible.',
  // Routes
  routes: {
    config: 'Configuration',
    settings: 'Paramètres',
    send: 'Envoyer',
    txs: 'Transactions',
    receive: 'Recevoir',
    home: 'Accueil',
    supcurr: 'Pièces connues',
    suplang: 'Langues connues',
    keystore: 'Exporter la clé',
    supnet: 'Supported Networks',
  },
  // About Component
  about: {
    version: 'Version:',
    author: 'Auteurs:',
    funded: 'Fondé Par:',
    contact: 'Contacter Nous:',
    translators: 'Le Traducteur:',
  },
  // Cordova Component
  cordova: {
    signin: 'Se connecter',
    error_screenlock: 'Veuillez activer le verrouillage de le écran sur votre appareil. Cette application ne peut pas fonctionner sans elle.',
    error_sec_storage: 'Le application n y a pas pu configurer le stockage sécurisé en raison de une erreur inconnue. Le application ne peut pas fonctionner sans elle.',
    title: 'Connectez-vous à votre portefeuille avec le authentification biométrique',
    error_screenlock_changed: 'Il semble que vous ayez modifié / supprimé le verrouillage de écran. Veuillez configurer un verrouillage de écran et réinstaller le application.',
  },
  // Nav Drawer component
  nav: {
    about: 'À propos',
    signout: 'Déconnexion',
  },
  // Manin layout
  main: {
    cache: 'Les données ne sont pas encore mises en cache. Veuillez réessayer en ligne',
  },
  // 404 Page
  error_404: {
    sorry: 'Désolé, rien ici ...',
  },
  // Keystore
  keystore: {
    fail: 'Impossible de générer la clé, veuillez nous contacter svp.',
    success: 'La clé a bien été créé.',
    message: 'Copiez simplement la clé généré et collez-le dans un fichier appelé keystore.json - Vous pouvez ensuite utiliser votre portefeuille mobile sur MyEtherWallet ou MyCrypto. Lorsque vous êtes invité à entrer votre mot de passe, vous utilisez votre épingle de application.',
  },
  // Home Page
  home: {
    balance: 'Portfolio',
    mcap: 'Capitalisation du marché:',
    volume: 'Volume (USD): $',
    mdata_error: 'Impossible de récupérer les données de marché demandées',
    last_tx_in: 'Dernier TX Recu:',
    last_tx_out: 'Dernier TX Expédié:',
    receive: 'Recevoir',
    send: 'Expédié',
    website: 'Ether-1 Site',
    settings: 'Paramètres de la application',
    txs: 'Transactions',
    error_getting_txs: 'Erreur lors de la récupération de la transactions',
    copied: 'Texte copié',
    not_signed_in: 'Please Sign in',
    markets_not_supported: 'Market Stats Not Supported on:',
    conv_not_supported: 'Price Conversion Not Supported on:',
    transactions_not_supported: 'TX Tracking is not available on:'
  },
  // User Index (Wallet Setup)
  index: {
    welcome: 'Bienvenue à la',
    name: 'Ether-1 Mobile Wallet !',
    before: 'Avant de commencer, nous avons quelques avis importants à passer en premier.',
    attention: 'Veuillez prêter une attention particulière aux éléments suivants:',
    access: 'Nous ne pouvons pas accéder à votre portefeuille.',
    reset: 'Nous ne pouvons pas réinitialiser votre code PIN.',
    backup: 'Sauvegardez votre clé privée.',
    client: 'Vous êtes responsable de votre portefeuille, la application est entièrement côté client et utilise uniquement notre RPC pour diffuser les transactions.',
    pin: "Si vous désactivez l'identifiant PIN, Face ou Touch de votre téléphone, vous perdrez l'accès à votre portefeuille et à vos fonds, c'est pourquoi vous devez sauvegarder votre clé privée",
    understand: 'Je comprends',
    setting: "Nous sommes occupés à configurer votre",
    wallet: 'Ether-1 Wallet',
    address: 'Voici votre adresse de portefeuille unique:',
    pkey: 'Ci-dessous est votre clé privée:',
    backup_pkey: 'Oubliez pas de sauvegarder votre clé privée!',
    got_it: "J'ai compris!",
    set: "Vous êtes prêt, votre",
    ready: 'est prêt!',
    by: 'par:',
    funded: 'financé',
    developed: 'développé',
    the_wallet: 'Le Ether-1 Wallet était',
    secure: 'Sécuriser mon portefeuille',
    encrypt: 'Chiffrez votre portefeuille:',
    wallet_name: 'Nom du portefeuille',
    use_pin: 'Entrez une PIN unique',
    confirm: 'Confirmez votre code PIN',
    required_name: 'Un nom de portefeuille est requis',
    required_pin: 'Une PIN est requise',
    retype_pin: 'Veuillez retaper votre code PIN pour confirmer',
    no_match: 'Les PINS ne correspondent pas',
    weak_pin: 'Le PIN choisie est très faible. Il doit comporter au moins 10 caractères et avoir un numéro.',
    copied: 'Texte copié',
    language: 'Veuillez sélectionner votre langue préférée:',
  },
  // Receive Page
  receive: {
    scan: 'Scannez le code QR pour recevoir',
    address: 'Adresse',
    warning: "Vous ne pouvez recevoir EVM coins qu'à cette adresse!",
    current_price: 'Prix actuel en',
    wallet_addr: 'Adresse du portefeuille',
    copied: 'Texte copié',
  },
  // Send Page
  send: {
    recent: 'Récent:',
    no_recent: 'Aucun transfert récent',
    no_contacts: 'Aucun contact ajouté',
    send_to: 'Combien souhaitez-vous envoyer à',
    add_contact: 'Ajouter le contact',
    name: 'Nom:',
    address: 'Adresse:',
    save: 'Sauver',
    delete: 'Supprimer le contact',
    copy_address: "Copier l'adresse",
    invalid_address: 'Adresse invalide',
    not_pasted: 'Impossible de coller',
    cancelled_scan: 'Scan annulé',
    unable_scan: 'Scan Impossible',
    scan_prompt: "Scanner le code QR de l'adresse",
    contact_added: 'Contact ajouté',
    enter_name: 'Entrez le nom:',
    enter_address: "Entrer l'adresse:",
    exists: 'a déjà cette adresse',
    copied: 'Adresse copiée',
    sending: 'Envoi de pièces',
    app_error: "Erreur inattendue, veuillez réinstaller l'application",
    tx_success: 'TRANSACTION TERMINEE',
    tx_failed: 'LA TRANSACTION A ÉCHOUÉ',
    about_black: 'À propos etho.black',
    about_ncr: 'À propos 3rd Party Developer (newCodeRunner)',
    stats: 'Ether-1 Statistiques du réseau',
    git: 'Ether-1 Github',
  },
  // Settings Page
  settings: {
    node_stats: 'Status de Node:',
    chain_id: 'ChainID:',
    Blockheight: 'Blockheigh Actuelle:',
    version: 'Node Version:',
    sync_status: 'Sync Status:',
    app: "Paramètres de l'application",
    select_currency: 'SÉLECTIONNEZ VOTRE MONNAIE:',
    select_language: 'CHOISISSEZ VOTRE LANGUE:',
    about: 'À propos Black Wallet:',
    about_etho: 'À propos Ether-1:',
    error_offline: 'Hors Ligne',
    keystore: 'GENERATE KEYSTORE',
    select_network: 'Select Blockchain',
  },
  // SupportedCurrencies Page
  SupportedCurrencies: {
    changed: 'Devise changée en: ',
  },
  // SupportedLanguages
  SupportedLanguages: {
    changed: 'Langue changée en: ',
  },
  // Transactions
  txs: {
    recent_txs: 'Transferts récents',
    no_txs: 'Aucun transfert effectué dans les 1000 derniers blocs.',
    retrieved: 'Transactions récupérées',
    error: 'Erreur lors de la récupération de la transactions',
  },
  // Currency Symbols - Do Not Change.
  etho: 'ETHO',
  zar: 'R',
  usd: '$',
  eur: '€',
  ltc: 'Ł',
  btc: '₿',
  eth: 'Ξ',
  bch: 'BCH',
  bnb: 'BNB',
  eos: 'EOS',
  xrp: 'XRP',
  xlm: 'XLM',
  aed: 'د.إ',
  ars: '$',
  aud: '$',
  bdt: '৳',
  bhd: '.د.ب',
  bmd: '$',
  brl: 'R$',
  cad: '$',
  chf: 'Fr',
  clp: '$',
  cny: '¥',
  czk: 'Kč',
  dkk: 'Kr.',
  gbp: '£',
  hkd: '$',
  huf: 'Ft',
  idr: 'Rp',
  ils: '₪',
  inr: '₹',
  jpy: '¥',
  krw: '₩',
  kwd: 'د.ك',
  lkr: 'Rs',
  mmk: 'K',
  mxn: '$',
  myr: 'RM',
  nok: 'kr',
  nzd: '$',
  php: '₱',
  pkr: '₱',
  pln: 'zł',
  rub: '₽',
  sar: '﷼‎,',
  sek: 'kr',
  sgd: '$',
  thb: '฿',
  try: '₺',
  twd: '$',
  uah: '₴',
  vef: 'Bs.',
  vnd: '₫',
  xdr: 'SDR.',
  xag: 'XAG',
  xau: 'XAU',
};
